export const HttpResponse = {
    SERVER_ERROR: "Internel server error",
    USER_EXIST: "User already exist",
    PAGE_NOT_FOUND: "Route not found",
    USER_NOT_FOUND: "User not found",
    USER_REGISTERED: "User registered successfully",
    PASSWORD_INCORRECT: "Incorrect password, try again",
    NO_ACCESS_TOKEN: "Token not provided",
    NO_REFRESH_TOKEN: "Refresh token not provided",
    NO_RESET_TOKEN: "Reset token not provided",
    NO_DECODED_TOKEN: "Couldn't decode token",
    GRPC_REGISTER_ERROR: "Failed to register user in Auth Service",
    TUTOR_EMAIL_EXIST_ERROR: "This email is already registered as a student. Please use a different email.",
    PROFILE_UPDATED: "Profile updated successfully",
    PROFILE_UPDATE_ERROR: "Failed to update profile",
    USERNAME_EXIST: "Username already choosen. Please choose something else",
    SKILL_ADDED: "Skill added",
    SKILL_EDITED: "Skill updated",
    SKILL_DELETED: "Skill deleted",
    SKILL_EXIST: "Skill already exists",
    SKILL_NOT_FOUND: "Skill not found",
    USER_ID_NOT_FOUND: "UserId not found",
    EMAIL_NOT_FOUND: "Email not found",
    VERIFY_LINK_SEND: "Verification link send to your email, Please verify!",
    EMAIL_VERIFIED: "Email verified successfully",
    TUTOR_APPROVED: "Tutor approved successfully",
    TUTOR_BLOCKED: "Tutor blocked successfully",
    TUTOR_UNBLOCKED: "Tutor unblocked successfully",
    TUTOR_NOT_FOUND: "Tutor not found",
    USER_BLOCKED: "User blocked successfully",
    USER_UNBLOCKED: "User unblocked successfully",
    PREMIUM_REVOKED: "Premium membership revoked",
}